package tests

import (
	"../p1"
	"fmt"
	"io/ioutil"
	"testing"
)

func TestExt(t *testing.T) {
	mpt := new(p1.MerklePatriciaTrie)
	mpt.Initial()
	mpt.Insert("a", "apple")
	mpt.Insert("b", "banana")
	inserted_trie := mpt.Order_nodes()
	mpt.Insert("", "new")
	check_mpt(mpt.Order_nodes(),"./mpt_tests/ext_010.txt", t)
	mpt.Delete("c")
	check_mpt(mpt.Order_nodes(),"./mpt_tests/ext_010.txt", t)
	mpt.Delete("")
	check_eq(mpt.Order_nodes(), inserted_trie, t)

	mpt.Initial()
	mpt.Insert("p", "apple")
	mpt.Insert("aa", "banana")
	mpt.Insert("ap", "orange")
	inserted_trie = mpt.Order_nodes()
	mpt.Insert("b", "new")
	check_mpt(mpt.Order_nodes(),"./mpt_tests/ext_011.txt", t)
	mpt.Delete("c")
	check_mpt(mpt.Order_nodes(),"./mpt_tests/ext_011.txt", t)
	mpt.Delete("b")
	check_eq(mpt.Order_nodes(), inserted_trie, t)

	mpt.Initial()
	mpt.Insert("p", "apple")
	mpt.Insert("aa", "banana")
	mpt.Insert("ap", "orange")
	inserted_trie = mpt.Order_nodes()
	mpt.Insert("ba", "new")
	check_mpt(mpt.Order_nodes(),"./mpt_tests/ext_013.txt", t)
	mpt.Delete("c")
	check_mpt(mpt.Order_nodes(),"./mpt_tests/ext_013.txt", t)
	mpt.Delete("ba")
	check_eq(mpt.Order_nodes(), inserted_trie, t)

	mpt.Initial()
	mpt.Insert("aa", "apple")
	mpt.Insert("ab", "banana")
	inserted_trie = mpt.Order_nodes()
	mpt.Insert("", "new")
	check_mpt(mpt.Order_nodes(),"./mpt_tests/ext_030.txt", t)
	mpt.Delete("c")
	check_mpt(mpt.Order_nodes(),"./mpt_tests/ext_030.txt", t)
	mpt.Delete("")
	check_eq(mpt.Order_nodes(), inserted_trie, t)

	mpt.Initial()
	mpt.Insert("p", "apple")
	mpt.Insert("aaa", "banana")
	mpt.Insert("aap", "orange")
	inserted_trie = mpt.Order_nodes()
	mpt.Insert("b", "new")
	check_mpt(mpt.Order_nodes(),"./mpt_tests/ext_031.txt", t)
	mpt.Delete("c")
	check_mpt(mpt.Order_nodes(),"./mpt_tests/ext_031.txt", t)
	mpt.Delete("b")
	check_eq(mpt.Order_nodes(), inserted_trie, t)

	mpt.Initial()
	mpt.Insert("p", "apple")
	mpt.Insert("aaa", "banana")
	mpt.Insert("aap", "orange")
	inserted_trie = mpt.Order_nodes()
	mpt.Insert("ba", "new")
	check_mpt(mpt.Order_nodes(),"./mpt_tests/ext_033.txt", t)
	mpt.Delete("c")
	check_mpt(mpt.Order_nodes(),"./mpt_tests/ext_033.txt", t)
	mpt.Delete("ba")
	check_eq(mpt.Order_nodes(), inserted_trie, t)

	mpt.Initial()
	mpt.Insert("aa", "apple")
	mpt.Insert("ap", "banana")
	inserted_trie = mpt.Order_nodes()
	mpt.Insert("b", "new")
	check_mpt(mpt.Order_nodes(),"./mpt_tests/ext_111.txt", t)
	mpt.Delete("c")
	check_mpt(mpt.Order_nodes(),"./mpt_tests/ext_111.txt", t)
	mpt.Delete("b")
	check_eq(mpt.Order_nodes(), inserted_trie, t)

	mpt.Initial()
	mpt.Insert("aa", "apple")
	mpt.Insert("ap", "banana")
	inserted_trie = mpt.Order_nodes()
	mpt.Insert("bc", "new")
	check_mpt(mpt.Order_nodes(),"./mpt_tests/ext_113.txt", t)
	mpt.Delete("c")
	check_mpt(mpt.Order_nodes(),"./mpt_tests/ext_113.txt", t)
	mpt.Delete("bc")
	check_eq(mpt.Order_nodes(), inserted_trie, t)

	mpt.Initial()
	mpt.Insert("p", "apple")
	mpt.Insert("aaaa", "banana")
	mpt.Insert("aaap", "orange")
	inserted_trie = mpt.Order_nodes()
	mpt.Insert("a", "new")
	check_mpt(mpt.Order_nodes(),"./mpt_tests/ext_140.txt", t)
	mpt.Delete("c")
	check_mpt(mpt.Order_nodes(),"./mpt_tests/ext_140.txt", t)
	mpt.Delete("a")
	check_eq(mpt.Order_nodes(), inserted_trie, t)

	mpt.Initial()
	mpt.Insert("aaa", "apple")
	mpt.Insert("aap", "banana")
	inserted_trie = mpt.Order_nodes()
	mpt.Insert("b", "new")
	check_mpt(mpt.Order_nodes(),"./mpt_tests/ext_131.txt", t)
	mpt.Delete("c")
	check_mpt(mpt.Order_nodes(),"./mpt_tests/ext_131.txt", t)
	mpt.Delete("b")
	check_eq(mpt.Order_nodes(), inserted_trie, t)

	mpt.Initial()
	mpt.Insert("aaa", "apple")
	mpt.Insert("aap", "banana")
	inserted_trie = mpt.Order_nodes()
	mpt.Insert("bc", "new")
	check_mpt(mpt.Order_nodes(),"./mpt_tests/ext_133.txt", t)
	mpt.Delete("c")
	check_mpt(mpt.Order_nodes(),"./mpt_tests/ext_133.txt", t)
	mpt.Delete("bc")
	check_eq(mpt.Order_nodes(), inserted_trie, t)
}

func TestLeaf(t *testing.T) {
	mpt := new(p1.MerklePatriciaTrie)
	mpt.Initial()
	mpt.Insert("a", "apple")
	mpt.Insert("b", "banana")
	mpt.Insert("a", "new")
	check_mpt(mpt.Order_nodes(),"./mpt_tests/leaf_000.txt", t)
	mpt.Delete("c")
	check_mpt(mpt.Order_nodes(),"./mpt_tests/leaf_000.txt", t)
	mpt.Delete("a")
	check_mpt(mpt.Order_nodes(),"./mpt_tests/delete_basic_1.txt", t)

	mpt.Initial()
	mpt.Insert("a", "apple")
	mpt.Insert("b", "banana")
	mpt.Insert("ab", "new")
	check_mpt(mpt.Order_nodes(),"./mpt_tests/leaf_002.txt", t)
	mpt.Delete("c")
	check_mpt(mpt.Order_nodes(),"./mpt_tests/leaf_002.txt", t)
	mpt.Delete("ab")
	check_mpt(mpt.Order_nodes(),"./mpt_tests/basic_0.txt", t)

	mpt.Initial()
	mpt.Insert("a", "apple")
	mpt.Insert("p", "banana")
	inserted_trie := mpt.Order_nodes()
	mpt.Insert("b", "new")
	check_mpt(mpt.Order_nodes(),"./mpt_tests/leaf_011.txt", t)
	mpt.Delete("c")
	check_mpt(mpt.Order_nodes(),"./mpt_tests/leaf_011.txt", t)
	mpt.Delete("b")
	check_eq(mpt.Order_nodes(), inserted_trie, t)

	mpt.Initial()
	mpt.Insert("a", "apple")
	mpt.Insert("p", "banana")
	inserted_trie = mpt.Order_nodes()
	mpt.Insert("bc", "new")
	check_mpt(mpt.Order_nodes(),"./mpt_tests/leaf_013.txt", t)
	mpt.Delete("c")
	check_mpt(mpt.Order_nodes(),"./mpt_tests/leaf_013.txt", t)
	mpt.Delete("bc")
	check_eq(mpt.Order_nodes(), inserted_trie, t)

	mpt.Initial()
	mpt.Insert("ap", "apple")
	inserted_trie = mpt.Order_nodes()
	mpt.Insert("", "new")
	check_mpt(mpt.Order_nodes(),"./mpt_tests/leaf_040.txt", t)
	mpt.Delete("c")
	check_mpt(mpt.Order_nodes(),"./mpt_tests/leaf_040.txt", t)
	mpt.Delete("")
	check_eq(mpt.Order_nodes(), inserted_trie, t)

	mpt.Initial()
	mpt.Insert("aab", "apple")
	mpt.Insert("app", "banana")
	inserted_trie = mpt.Order_nodes()
	mpt.Insert("ac", "new")
	check_mpt(mpt.Order_nodes(),"./mpt_tests/leaf_031.txt", t)
	mpt.Delete("c")
	check_mpt(mpt.Order_nodes(),"./mpt_tests/leaf_031.txt", t)
	mpt.Delete("ac")
	check_eq(mpt.Order_nodes(), inserted_trie, t)

	mpt.Initial()
	mpt.Insert("aab", "apple")
	mpt.Insert("app", "banana")
	inserted_trie = mpt.Order_nodes()
	mpt.Insert("ace", "new")
	check_mpt(mpt.Order_nodes(),"./mpt_tests/leaf_033.txt", t)
	mpt.Delete("c")
	check_mpt(mpt.Order_nodes(),"./mpt_tests/leaf_033.txt", t)
	mpt.Delete("ace")
	check_eq(mpt.Order_nodes(), inserted_trie, t)

	mpt.Initial()
	mpt.Insert("p", "banana")
	inserted_trie = mpt.Order_nodes()
	mpt.Insert("a", "apple")
	mpt.Insert("a", "new")
	check_mpt(mpt.Order_nodes(),"./mpt_tests/leaf_100.txt", t)
	mpt.Delete("c")
	check_mpt(mpt.Order_nodes(),"./mpt_tests/leaf_100.txt", t)
	mpt.Delete("a")
	check_eq(mpt.Order_nodes(), inserted_trie, t)

	mpt.Initial()
	mpt.Insert("a", "apple")
	mpt.Insert("p", "banana")
	inserted_trie = mpt.Order_nodes()
	mpt.Insert("abc", "new")
	check_mpt(mpt.Order_nodes(),"./mpt_tests/leaf_104.txt", t)
	mpt.Delete("c")
	check_mpt(mpt.Order_nodes(),"./mpt_tests/leaf_104.txt", t)
	mpt.Delete("abc")
	check_eq(mpt.Order_nodes(), inserted_trie, t)

	mpt.Initial()
	mpt.Insert("a", "apple")
	inserted_trie = mpt.Order_nodes()
	mpt.Insert("b", "new")
	check_mpt(mpt.Order_nodes(),"./mpt_tests/leaf_111.txt", t)
	mpt.Delete("c")
	check_mpt(mpt.Order_nodes(),"./mpt_tests/leaf_111.txt", t)
	mpt.Delete("b")
	check_eq(mpt.Order_nodes(), inserted_trie, t)

	mpt.Initial()
	mpt.Insert("a", "apple")
	inserted_trie = mpt.Order_nodes()
	mpt.Insert("bc", "new")
	check_mpt(mpt.Order_nodes(),"./mpt_tests/leaf_113.txt", t)
	mpt.Delete("c")
	check_mpt(mpt.Order_nodes(),"./mpt_tests/leaf_113.txt", t)
	mpt.Delete("bc")
	check_eq(mpt.Order_nodes(), inserted_trie, t)

	mpt.Initial()
	mpt.Insert("ap", "apple")
	inserted_trie = mpt.Order_nodes()
	mpt.Insert("b", "new")
	check_mpt(mpt.Order_nodes(),"./mpt_tests/leaf_131.txt", t)
	mpt.Delete("c")
	check_mpt(mpt.Order_nodes(),"./mpt_tests/leaf_131.txt", t)
	mpt.Delete("b")
	check_eq(mpt.Order_nodes(), inserted_trie, t)

	mpt.Initial()
	mpt.Insert("ap", "apple")
	inserted_trie = mpt.Order_nodes()
	mpt.Insert("bp", "new")
	check_mpt(mpt.Order_nodes(),"./mpt_tests/leaf_133.txt", t)
	mpt.Delete("c")
	check_mpt(mpt.Order_nodes(),"./mpt_tests/leaf_133.txt", t)
	mpt.Delete("bp")
	check_eq(mpt.Order_nodes(), inserted_trie, t)
}

func TestDeleteBasic(t *testing.T) {
	mpt := new(p1.MerklePatriciaTrie)
	mpt.Initial()
	mpt.Insert("a", "apple")
	mpt.Insert("b", "banana")
	mpt.Delete("a")
	check_mpt(mpt.Order_nodes(),"./mpt_tests/delete_basic_1.txt", t)

	mpt.Initial()
	mpt.Insert("a", "apple")
	mpt.Insert("b", "banana")
	mpt.Delete("c")
	check_mpt(mpt.Order_nodes(),"./mpt_tests/delete_basic_0.txt", t)

	mpt.Initial()
	mpt.Insert("aa", "apple")
	mpt.Insert("abb", "banana")
	mpt.Delete("a")
	check_mpt(mpt.Order_nodes(),"./mpt_tests/delete_basic_2.txt", t)
}

func TestBranch(t *testing.T) {
	mpt := new(p1.MerklePatriciaTrie)
	mpt.Initial()
	mpt.Insert("aa", "apple")
	mpt.Insert("ap", "banana")
	inserted_trie := mpt.Order_nodes()
	mpt.Insert("a", "new")
	check_mpt(mpt.Order_nodes(),"./mpt_tests/branch_nv_np.txt", t)
	mpt.Delete("c")
	check_mpt(mpt.Order_nodes(),"./mpt_tests/branch_nv_np.txt", t)
	mpt.Delete("a")
	check_eq(mpt.Order_nodes(), inserted_trie, t)

	mpt.Initial()
	mpt.Insert("a", "old")
	mpt.Insert("aa", "apple")
	mpt.Insert("ap", "banana")
	mpt.Insert("a", "new")
	check_mpt(mpt.Order_nodes(),"./mpt_tests/branch_v_np.txt", t)
	mpt.Delete("c")
	check_mpt(mpt.Order_nodes(),"./mpt_tests/branch_v_np.txt", t)
	mpt.Delete("a")
	expected_mpt := new(p1.MerklePatriciaTrie)
	expected_mpt.Initial()
	expected_mpt.Insert("aa", "apple")
	expected_mpt.Insert("ap", "banana")
	check_eq(mpt.Order_nodes(), expected_mpt.Order_nodes(), t)

	mpt.Initial()
	mpt.Insert("a", "apple")
	mpt.Insert("b", "banana")
	inserted_trie = mpt.Order_nodes()
	mpt.Insert("c", "new")
	check_mpt(mpt.Order_nodes(),"./mpt_tests/branch_nv_p.txt", t)
	mpt.Delete("cc")
	check_mpt(mpt.Order_nodes(),"./mpt_tests/branch_nv_p.txt", t)
	mpt.Delete("c")
	check_eq(mpt.Order_nodes(), inserted_trie, t)

	mpt.Initial()
	mpt.Insert("aa", "apple")
	mpt.Insert("ap", "banana")
	mpt.Insert("a", "old")
	inserted_trie = mpt.Order_nodes()
	mpt.Insert("aA", "new")
	check_mpt(mpt.Order_nodes(),"./mpt_tests/branch_v_p.txt", t)
	mpt.Delete("c")
	check_mpt(mpt.Order_nodes(),"./mpt_tests/branch_v_p.txt", t)
	mpt.Delete("aA")
	check_eq(mpt.Order_nodes(), inserted_trie, t)
}

func TestLeafBasic(t *testing.T) {
	mpt := new(p1.MerklePatriciaTrie)
	mpt.Initial()
	mpt.Insert("a", "apple")
	mpt.Insert("b", "banana")
	check_mpt(mpt.Order_nodes(),"./mpt_tests/basic_0.txt", t)

	mpt.Initial()
	mpt.Insert("a", "apple")
	mpt.Insert("p", "banana")
	check_mpt(mpt.Order_nodes(),"./mpt_tests/basic_1.txt", t)

	mpt.Initial()
	mpt.Insert("a", "apple")
	check_mpt(mpt.Order_nodes(),"./mpt_tests/basic_2.txt", t)
}

func TestExtBasic(t *testing.T) {
	mpt := new(p1.MerklePatriciaTrie)
	mpt.Initial()
	mpt.Insert("a", "apple")
	mpt.Insert("b", "banana")
	check_mpt(mpt.Order_nodes(), "./mpt_tests/ext_basic_1.txt", t)

	mpt.Initial()
	mpt.Insert("aa", "apple")
	mpt.Insert("ap", "banana")
	check_mpt(mpt.Order_nodes(),"./mpt_tests/ext_basic_2.txt", t)

	mpt.Initial()
	mpt.Insert("aa", "apple")
	mpt.Insert("ab", "banana")
	check_mpt(mpt.Order_nodes(),"./mpt_tests/ext_basic_3.txt", t)

	mpt.Initial()
	mpt.Insert("aaa", "apple")
	mpt.Insert("aap", "banana")
	check_mpt(mpt.Order_nodes(),"./mpt_tests/ext_basic_4.txt", t)

	mpt.Initial()
	mpt.Insert("p", "apple")
	mpt.Insert("aa", "banana")
	mpt.Insert("ap", "orange")
	check_mpt(mpt.Order_nodes(),"./mpt_tests/ext_basic_5.txt", t)
}

func check_mpt(mpt_string string, file_path string, t *testing.T) {
	content, _ := ioutil.ReadFile(file_path)
	if string(content) != mpt_string {
		fmt.Println("=========Real============")
		fmt.Println(mpt_string)
		fmt.Println("=========Expcected============")
		fmt.Println(string(content))
		fmt.Println("=====================")
		t.Fail()
	}
}

func check_eq(real string, expected string, t *testing.T) {
	if real != expected {
		fmt.Println("=========Real============")
		fmt.Println(real)
		fmt.Println("=========Expcected============")
		fmt.Println(expected)
		fmt.Println("=====================")
		t.Fail()
	}
}

func TestCompactEncode(t *testing.T) {
	p1.TestCompact()
}
